// Client/src/app/pages/homepage/homepage.component.ts
import { Component } from '@angular/core';
import { HomepageService } from './homepage.service';
import { Job, JobsQuickInfo } from 'src/app/shared/models/jobOffer';
import {TechList} from "../../shared/constants/constants";

@Component({
  selector: 'app-homepage',
  templateUrl: './homepage.component.html',
  styleUrls: ['./homepage.component.scss']
})
export class HomepageComponent {

  TechList = TechList;

  user = {
    email:`test@example.com`
  }

  jobs?: JobsQuickInfo[];
  searchTerm: string = '';
  locationTerm: string = '';

  constructor (private homepageService: HomepageService) { }

  ngAfterViewInit(): void {
    this.homepageService.getJobs(this.searchTerm, this.locationTerm).subscribe(res => {
      this.jobs = res.methodResult;
    })
  }

  getTechName(selectedNumber: string): string {
    const key = Object.keys(TechList).find(key => TechList[key] === Number(selectedNumber));
    return key || selectedNumber; // Zwracamy pusty ciąg znaków, jeśli nie znaleziono klucza
  }

  searchJobs() {
    this.homepageService.getJobs(this.searchTerm, this.locationTerm).subscribe(res => {
      this.jobs = res.methodResult;
    });
  }
  // company = {
  //   "longName": "T-Mobile Polska S.A.",
  //   "name": "T-Mobile",
  //   "image": '../../../assets/images/logoEmpty.png',
  //   "location": 'Poznan',
  // }

  // offers = [
  //   {
  //     "jobName": "Junior Fullstack Developer",
  //     "place": "Poznań",
  //     "tags": ["HTML", "CSS", "Java", "Angular"]
  //   }
  // ];
  protected readonly Number = Number;
}

<div class="custom-section">
    <div class="background-image"></div>
    <div class="content">
        <h1>{{'HomePage.Find job' | translate}}</h1>
        <div class="inputs">
            <input type="text" placeholder="Junior Java Developer..." class="finddev" [(ngModel)]="searchTerm"
                   (ngModelChange)="searchJobs()"/>
            <input type="text" placeholder="Poznań" class="locatedev" [(ngModel)]="locationTerm"
                   (ngModelChange)="searchJobs()"/>
        </div>
    </div>
</div>

<div class="info-section">
    <div class="title">
        <h1>{{'HomePage.Jobs' | translate}}</h1>
    </div>
    <div class="subtitle">
        <h2>{{'HomePage.Find offers' | translate}}</h2>
    </div>
</div>

<div class="jobOffers" id="ofert">
    <div class="offer" *ngFor="let job of jobs">
        <div class="left">
            <a href="/joboffer/{{job.job.id}}" class="logocompany">
                <img class="avatar" alt="avatar" src="{{job.company.logo ? job.company.logo : '../../../assets/images/logoEmpty.png'}}">
            </a>
            <div class="companyName">
                <a href="/joboffer/{{job.job.id}}" class="jobname">
                    <span>{{job.job.name | capitalize}}</span>
                </a>
                <a href="/company/{{job.company.id}}" class="companyname">
                    <span>{{job.company.name | capitalize}}</span>
                </a>
            </div>
        </div>
        <div class="center">
            <div class="tags" *ngFor="let technology of job.jobTechnologies.slice(0, 4)">
                <div class="tag" *ngIf="technology.icon !== ''">
                    {{ getTechName(technology.icon) | capitalize }}
                </div>
            </div>
        </div>
        <div class="right">
            <p>{{(job.job.image ? job.job.image : job.company.headquarteraddress) | capitalize}}</p>
            <button mat-button class="applyButton" [routerLink]="'/joboffer/' + job.job.id"><span>{{'HomePage.See offer' | translate}}</span></button>
        </div>
    </div>
</div>

// XerionIntegration/xerionfront/src/pages/HomePage.tsx
import React, { useState } from 'react';

const JobOffers: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState<string>('');
  const [locationTerm, setLocationTerm] = useState<string>('');
  const [jobs, setJobs] = useState<any[]>([]);

  const searchJobs = () => {
    console.log('Search triggered with:', searchTerm, locationTerm);
    // Dodaj logikę wyszukiwania tutaj
  };

  const getTechName = (icon: string): string => {
    // Przykładowa logika pobierania nazwy technologii
    return icon;
  };

  return (
    <div>
      {/* Sekcja główna */}
      <div className="custom-section">
        <div className="background-image"></div>
        <div className="content">
          <h1>{'HomePage.Find job'}</h1>
          <div className="inputs">
            <input
              type="text"
              placeholder="Junior Java Developer..."
              className="finddev"
              value={searchTerm}
              onChange={(e) => {
                setSearchTerm(e.target.value);
                searchJobs();
              }}
            />
            <input
              type="text"
              placeholder="Poznań"
              className="locatedev"
              value={locationTerm}
              onChange={(e) => {
                setLocationTerm(e.target.value);
                searchJobs();
              }}
            />
          </div>
        </div>
      </div>

      {/* Sekcja informacji */}
      <div className="info-section">
        <div className="title">
          <h1>{'HomePage.Jobs'}</h1>
        </div>
        <div className="subtitle">
          <h2>{'HomePage.Find offers'}</h2>
        </div>
      </div>

      {/* Oferty pracy */}
      <div className="jobOffers" id="ofert">
        {jobs.map((job) => (
          <div className="offer" key={job.job.id}>
            <div className="left">
              <a href={`/joboffer/${job.job.id}`} className="logocompany">
                <img
                  className="avatar"
                  alt="avatar"
                  src={job.company.logo || '../../../assets/images/logoEmpty.png'}
                />
              </a>
              <div className="companyName">
                <a href={`/joboffer/${job.job.id}`} className="jobname">
                  <span>{job.job.name}</span>
                </a>
                <a href={`/company/${job.company.id}`} className="companyname">
                  <span>{job.company.name}</span>
                </a>
              </div>
            </div>
            <div className="center">
              <div className="tags">
                {job.jobTechnologies.slice(0, 4).map((technology, index) => (
                  <div className="tag" key={index}>
                    {technology.icon && getTechName(technology.icon)}
                  </div>
                ))}
              </div>
            </div>
            <div className="right">
              <p>{job.job.image || job.company.headquarteraddress}</p>
              <button
                className="applyButton"
                onClick={() => (window.location.href = `/joboffer/${job.job.id}`)}
              >
                <span>{'HomePage.See offer'}</span>
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default JobOffers;
